### ISSUE TITLE
I have met this error:

### ISSUE THREAD

**Issue by bemoregt** [mcarletti/image-to-value-regression-pt#1]
HI, @mcarletti 

I have met this error:

FileNotFoundError: [Errno 2] No such file or directory: '/media/Data/datasets/image-to-value-regression-using-deep-learning/sportsmen_crop/bin_data/HeadLegLess.mat'

What's wrong with me?

Thanks in advance.

from @bemoregt.

**Comment by mcarletti** [comment]
Hi @bemoregt  

Note that this is a work-in-progress project and the code has to be updated.

Anyway, the error is related to the missing data file. There should be many other mat files, which are the binarized version of my dataset (FATDATA), but unfortunately I'm still not allowed to distribute any of the data collected so far. By the end of the summer, I think I'l be able to upload and update everything.

The only dataset you can freely retrieve to test the current code is the [IMDB-WIKI](https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/) dataset. I used the lighter version of the data (WIKI face-only, 1 GB) which I previously aligned with a face-aligment algorithm.

To use this dataset, in my `main.py` file you have to modify the task variable (line 39) from `fat-from-depth` to `age-from-faces`.

Ciao.

**Comment by bemoregt** [comment]
Hi, @mcarletti 

Thanks a lot.

I will try that.

from @bemoregt.
